name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: API meta
        id: api_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/springbootapp
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./springbootapp
          push: true
          tags: ${{ steps.api_meta.outputs.tags }}

      - name: Angular meta
        id: ng_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/angular-app
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build & push Angular
        uses: docker/build-push-action@v6
        with:
          context: ./angular
          push: true
          tags: ${{ steps.ng_meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_APP_PATH }}
            docker compose pull
            docker compose up -d
